# Generated by Django 2.0.4 on 2021-03-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auther',
            new_name='author',
        ),
    ]
